apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-app
spec:
  selector:
    matchLabels:
      app: employee-app
  replicas: 1
  template:
    metadata:
      labels:
        app: employee-app
    spec:
      containers:
      - name: nodejs
        image: devopsedu/employee
        ports:
        - containerPort: 8888
        env:
        - name: MONGO_URL
          value: mongodb://mongo:27017/employee
